### ISSUE TITLE
Pull request #3588 not ported to 1.6+

### ISSUE THREAD

**Issue by yakky** [openlibhums/janeway#5197]
**Describe the bug**
Pull request #3588 which improves review assignment withdrawing has not been ported to mainline

`ReviewAssignment.withdraw` has been introduced with PR #3588 on the 1.5 release branch, but it has never been ported to master branch and is then lost in any non 1.5 version

It should be reintroduced to restore the feature

**Janeway version**
1.6

**To Reproduce**

```python
ra = ReviewAssignment.objects.all().first()
ra.withdraw()
```

**Expected behavior**

ReviewAssignment is marked as withdrawn

**Actual behavior**

`AttributeError: 'ReviewAssignment' object has no attribute 'withdraw'` is raised

**Comment by ajrbyers** [comment]
We need to add a PR and resolve the conflicts see: https://github.com/openlibhums/janeway/compare/master...b_1_5_0
