### ISSUE TITLE
v.1.4.3-RC-4: Not compatible with Python 3.10.7 ?

### ISSUE THREAD

**Issue by cederom** [openlibhums/janeway#3198]
**Describe the bug**
* It seems that `v.1.4.3-RC-4` is not compatible with Python 3.10(.7)?
* All works fine with Python 3.6.9.

**Janeway version**
`v.1.4.3-RC-4`

**To Reproduce**
1. Setup Python `3.10.7` VirtualEnvironment.
2. Try `./manage install_janeway`.
3. See error reported in Logs section below.

**Expected behavior**
Current / upcoming release works fine with most recent Python version.

**Screenshots**
```
(venv3.10janeway) [fadeaway]$ python3 manage.py install_janeway
Traceback (most recent call last):
  File "/home/XXX/www/new.e-health.pl/janeway/manage.py", line 13, in <module>
    from django.core.management import execute_from_command_line
  File "/home/XXX/.local/venv3.10janeway/lib/python3.10/site-packages/django/core/management/__init__.py", line 13, in <module>
    from django.core.management.base import (
  File "/home/XXX/.local/venv3.10janeway/lib/python3.10/site-packages/django/core/management/base.py", line 17, in <module>
    from django.db.migrations.exceptions import MigrationSchemaMissing
  File "/home/XXX/.local/venv3.10janeway/lib/python3.10/site-packages/django/db/migrations/__init__.py", line 2, in <module>
    from .operations import *  # NOQA
  File "/home/XXX/.local/venv3.10janeway/lib/python3.10/site-packages/django/db/migrations/operations/__init__.py", line 1, in <module>
    from .fields import AddField, AlterField, RemoveField, RenameField
  File "/home/XXX/.local/venv3.10janeway/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 4, in <module>
    from django.db.models.fields import NOT_PROVIDED
  File "/home/XXX/.local/venv3.10janeway/lib/python3.10/site-packages/django/db/models/__init__.py", line 5, in <module>
    from django.db.models.deletion import (
  File "/home/XXX/.local/venv3.10janeway/lib/python3.10/site-packages/django/db/models/deletion.py", line 5, in <module>
    from django.db.models import signals, sql
  File "/home/XXX/.local/venv3.10janeway/lib/python3.10/site-packages/django/db/models/sql/__init__.py", line 2, in <module>
    from django.db.models.sql.query import *  # NOQA
  File "/home/XXX/.local/venv3.10janeway/lib/python3.10/site-packages/django/db/models/sql/query.py", line 11, in <module>
    from collections import Counter, Iterator, Mapping, OrderedDict
ImportError: cannot import name 'Iterator' from 'collections' (/home/XXX/.local/python/lib/python3.10/collections/__init__.py)
(venv3.10janeway) [fadeaway]$ pip install collections
```

**Desktop (please complete the following information):**
 - OS: Linux (shared hosting).
 - Browser: n/a.
 - Version: `Linux hosting 4.14.117-grsec-grsec+ #1 SMP Sat May 11 00:40:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`.
 - Python: `3.10.7`.

**Additional context**
* All works fine with Python 3.6.9.
```
$ ./manage.py install_janeway
/home/XXX/.local/venv3.6janeway/lib/python3.6/site-packages/jwt/utils.py:7: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
Operations to perform:
  Apply all migrations: admin, auth, carousel, cms, comms, contenttypes, copyediting, core, cron, discussion, django_summernote, featured, identifiers, journal, metrics, press, production, proofing, repository, review, sessions, submission, utils
Running migrations:
  Applying core.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying journal.0001_initial... OK
```

**Comment by joemull** [comment]
@StephDriver Yes I believe so.
